language: node_js

node_js:
  - "10"

os: 
  - osx
  - linux
  - windows

install:
  - npm install --only=prod
  - npm link --only=prod
  - npm install -g mocha
  - cd test
  - npm install file:modules/markomatic-template-test-1
  - npm install file:modules/markomatic-template-test-2
  - cd ..

script:
  - npm test
