language: node_js

node_js:
  - "10"

os: 
  - osx
  - linux
  - windows

install:
  - npm install file:test/modules/markomatic-template-test-1 --save-prod
  - npm install file:test/modules/markomatic-template-test-2 --save-prod
  - npm prune --production
  - npm link --only=prod
  - npm install -g mocha

script:
  - npm test
